version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - apt-get update && apt-get install -y awscli
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=803387083822.dkr.ecr.us-east-1.amazonaws.com/devops-assessment
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 803387083822.dkr.ecr.us-east-1.amazonaws.com/devops-assessment:$IMAGE_TAG .
      - docker tag 803387083822.dkr.ecr.us-east-1.amazonaws.com/devops-assessment:$IMAGE_TAG 803387083822.dkr.ecr.us-east-1.amazonaws.com/devops-assessment:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 803387083822.dkr.ecr.us-east-1.amazonaws.com/devops-assessment:$IMAGE_TAG
      - docker push 803387083822.dkr.ecr.us-east-1.amazonaws.com/devops-assessment:latest
      - echo Updating the Kubernetes deployment...
      - kubectl set image deployment/devops-challenge back-end=803387083822.dkr.ecr.us-east-1.amazonaws.com/devops-assessment:$IMAGE_TAG
      - echo Deployment completed on `date`
