apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-southeast-1

vpc:
  id: vpc-0abc85ded381a0dc9
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-06084a921a989e777
      us-east-1b:
        id: subnet-05956bb8546f6bdf6
    private:
      us-east-1a:
        id: subnet-0b5fb0d3d723c2d17
      us-east-1b:
        id: subnet-097feeb4795be2360

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
